default:
  golem_name: batchingsamples
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: /Users/cheungf/Library/CloudStorage/OneDrive-NationalInstitutesofHealth/R/golemosat
